# 管理系统数据库的信息。
# 如果直接使用scow-deployment提供的数据库，此部分内容不修改
db:
  host: db
  port: 3306
  user: root
  dbName: scow

# 获取作业相关配置
fetchJobs:
  # 源作业信息数据库的数据库信息
  db:
    host: sourcedb
    port: 3307
    user: root
    password: jobtablepassword
    dbName: jobs
    tableName: jobs
    # 数据库类型，可选mariadb或者mysql
    # 默认为mariadb
    # type: mariadb

  # 周期性获取数据
  periodicFetch:
    # 是否开启
    enabled: true
    # 周期的cron表达式
    cron: "10 */10 * * * *"

# 预定义的充值类型
predefinedChargingTypes:
  - 测试

# 创建账户时，账户名的规则。不设置就没有限制
# accountNamePattern:
  # 正则表达式
  # regex: ""

  # 出错时的消息
  # errorMessage: ""

# 创建用户相关配置
# createUser:

  # 是否允许用户从SCOW中创建用户
  # enabled: true

  # SCOW中创建用户界面是使用内置的（builtin）或者使用外置页面（external）
  # 默认builtin
  # type: builtin

  # 内置创建用户界面配置
  # builtin:
    # 用户ID的格式
    # userIdPattern:
      # 正则表达式
      # regex: ""

      # 出错时的消息
      # errorMessage: ""

  # 外置页面配置
  # external:
    # 外置页面URL
    # url: http://your-create-user-page.com


# 新增管理系统导航链接相关配置
# navLinks:

  # 链接名
  # text: ""

  # 链接地址，一级导航链接地址为可选填，二级导航链接地址为必填
  # url: ""

  # 是否打开新的页面，可选填，默认值为false
  # openInNewPage: true

  # 自定义图标地址,可选填
  # iconPath: ""

  # 可以看到这个链接的用户,可选填
  # 用户类型： user, accountUser, accountAdmin, accountOwner, tenantFinance, tenantAdmin, platformAdmin, platformFinance
  # allowedRoles: []

  # 二级导航,可选填
  # children:
    # 二级导航相关配置，与一级导航相同，但是url为必填配置，同时不允许再设置children
    # text: ""
    # url: ""
    # openInNewPage: true
    # iconPath: ""
    # allowedRoles: []
