# 这个应用的ID
id: pycharm

# 这个应用的名字
name: pycharm

# 这个应用的图标文件在公共文件下的路径
# logoPath: /test.svg

# 指定应用类型，vnc或者web
type: vnc

image:
  # 镜像名称
  name: pycharm
  # 镜像版本
  tag: v0.1

# VNC应用的配置
vnc:
  # 此X Session的xstartup脚本
  xstartup: |
    pycharm
