version: "3"

services:

  gateway:
    image: $IMAGE_BASE/gateway:$TAG
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.gateway

  mis-web-mis:
    image: $IMAGE_BASE/mis-web-mis:$TAG
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.mis-web
      args:
        - BASE_PATH=/mis

  mis-web-root:
    image: $IMAGE_BASE/mis-web-root:$TAG
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.mis-web
      args:
        - BASE_PATH=

  portal-web-portal:
    image: $IMAGE_BASE/portal-web-portal:$TAG
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.portal-web
      args:
        - BASE_PATH=/portal

  portal-web-root:
    image: $IMAGE_BASE/portal-web-root:$TAG
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.portal-web
      args:
        - BASE_PATH=

  mis-server:
    image: $IMAGE_BASE/mis-server:$TAG
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.mis-server

  job-server-slurm:
    image: $IMAGE_BASE/job-server-slurm:$TAG
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.job-server-slurm

  auth:
    image: $IMAGE_BASE/auth:$TAG
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.auth

  clusterops-slurm:
    image: $IMAGE_BASE/clusterops-slurm:$TAG
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.clusterops-slurm

