# 集群显示名称
displayName: hpc01
# displayName:
#   i18n:
#     default: 集群1
#     en: Cluster One
#     zh_cn: 集群1

adapterUrl: "192.168.88.101:8972"

loginNodes:
  # 登录节点展示名称
  - name: login
  # - name:
  #     i18n:
  #       default: 登录节点1
  #       en: loginNode1
  #       zh_cn: 登录节点1
    # 登录节点的IP或者域名
    # 如果设置的是域名，请确认此节点的/etc/hosts中包含了域名到IP的解析信息
    address: 192.168.88.102
