# 集群显示名称
displayName: hpc01Name

# 指定slurm配置
loginNodes:
  # 登录节点展示名称
  - name: login01
    # 登录节点的IP或者域名
    # 如果设置的是域名，请确认此节点的/etc/hosts中包含了域名到IP的解析信息
    address: login01
  - name: login02
    address: login02

# 适配器地址(ip地址:端口号)
adapterUrl: localhost:8972

# 门户系统代理网关节点配置
# proxyGateway:
#   # 带协议，不要以/结尾
#   url: http://10.2.3.2:1080

#   # 是否在这个机器上自动配置nginx
#   autoSetupNginx: true
