displayName: hpc01Name
adapterUrl: 0.0.0.0
loginNodes:
  - localhost:22222
# slurm:
#   partitions:
#       - name: compute
#         nodes: 3
#         mem: 262144
#         cores: 32
#         gpus: 0
#         qos:
#           - low
#           - normal
#           - high
#         comment: 说明

#       - name: GPU
#         nodes: 1
#         mem: 262144
#         cores: 48
#         gpus: 8
#         qos:
#           - low
#           - normal
#           - high
#           - highest
#         comment: 说明
