# 指定使用认证类型为LDAP
authType: ldap

# 在此部分输入LDAP的配置
ldap:
  # LDAP服务器地址。必填
  url: ldap://192.168.88.101

  # 进行LDAP操作的用户DN。默认为空
  bindDN: cn=Manager,ou=hpc,o=pku
  # 进行LDAP操作的用户密码。默认为空
  bindPassword: "admin"

  # 在哪个节点下搜索要登录的用户。必填
  searchBase: "ou=hpc,o=pku"
  # 搜索登录用户时的筛选器。必填
  userFilter: "(uid=*)"

  # 属性映射
  attrs:
    # LDAP中对应用户ID的属性名
    uid: uid

    # LDAP对应用户姓名的属性名
    # 此字段用于
    # 1. 登录时显示为用户的姓名
    # 2. 创建用户的时候把姓名信息填入LDAP
    # 3. 管理系统添加用户时，验证ID和姓名是否匹配
    #
    # 如果不设置此字段，那么
    # 1. 用户姓名为用户的ID
    # 2. 创建用户时姓名信息填入LDAP
    # 3. 管理系统添加用户时，不验证ID与姓名是否匹配
    name: cn

    # LDAP中对应用户的邮箱的属性名。可不填。此字段只用于在创建用户的时候把邮件信息填入LDAP。
    mail: mail

  # 添加用户的相关配置。必填
  addUser:
    # 增加用户节点时，把用户增加到哪个节点下
    userBase: "ou=People,ou=hpc,o=pku"

    # 用户的homeDirectory值。使用{{ userId }}代替新用户的用户名。默认如下
    homeDir: /data/home/{{ userId }}

    # LDAP增加用户时，新用户节点的DN中，第一个路径的属性的key。
    # 新用户节点的DN为{userIdDnKey}={用户ID},{userBase}
    # 如果不填写，则使用ldap.attrs.uid的值
    userIdDnKey: uid

    # 如何确定新用户的组。可取的值包括：
    # newGroupPerUser: 给每个用户创建新的组
    # oneGroupForAllUsers: 不创建新的组，给所有用户设定一个固定的组
    groupStrategy: newGroupPerUser

    newGroupPerUser:
      # 用户对应的新组应该加在哪个节点下
      groupBase: "ou=Group,ou=hpc,o=pku"

      # 新的组节点的DN中，第一个路径的属性的key。
      # 新的组节点的DN为{groupIdDnKey}={用户ID},{groupBase}
      # 如果不填写，则使用ldap.attrs.uid的值
      groupIdDnKey: cn

      # 组的节点应该额外拥有的属性值。可以使用 {{ 用户节点的属性key }}来使用用户节点的属性值
      # extraProps:
      #   greetings: hello this is group {{ userId }}

    # 如果groupStrategy设置为oneGroupForAllUsers，那么必须设置此属性
    oneGroupForAllUsers:
      # 用户的gidNumber属性的值
      gidNumber: 5000

    # 是否应该把新用户加到哪个LDAP组下。如果不填，则不加
    # addUserToLdapGroup: group

    # uid从多少开始。生成的用户的uid等于此值加上用户账户中创建的用户ID
    # 默认如下
    # uidStart: 66000

    # 用户项除了id、name和mail，还应该添加哪些属性。类型是个dict
    # 如果这里出现了名为uid, name或email的属性，这里的值将替代用户输入的值。
    # 属性值支持使用 {{ LDAP属性值key }} 格式来使用用户填入的值。
    # 例如：sn: "{{ cn }}"，那么添加时将会增加一个sn属性，其值为cn的属性，即为用户输入的姓名
    # extraProps:
    #   key: value
