# 管理系统数据库的信息。可以不修改
db:
  host: db
  port: 3306
  user: root
  dbName: scow

# 获取作业相关配置
fetchJobs:
  # 周期性获取数据
  periodicFetch:
    # 是否开启
    enabled: true
    # 周期的cron表达式
    cron: "*/10 * * * *"

# 预定义的充值类型
predefinedChargingTypes:
  - 测试

# 账户名的规则
accountNamePattern:
  # 正则表达式
  regex: "(a_)[a-z]+$"

  # 出错时的消息
  # errorMessage: ""

createUser:
  # 创建用户时，用户ID的规则。不设置就没有限制
  userIdPattern:
    # 正则表达式
    regex: "^[a-zA-Z0-9_]+$"
    # 出错时的消息
    errorMessage: "只能由字母、下划线、数字组成"
