# 这个应用的ID
id: emacs

# 这个应用的名字
name: emacs

# 这个应用的图标文件在公共文件下的路径
# logoPath: /test.svg

# 指定应用类型，vnc或者web
type: vnc

# 可以运行这个应用的节点地址
# 如果不设置nodes，则所有节点都可以运行
# nodes:
#   - t001
#   - t002

# VNC应用的配置
vnc:
  # 此X Session的xstartup脚本
  xstartup: |
    emacs -mm


# 交互式应用说明，选填。
# 类型为string或国际化文本类型
appComment: "<p>对上方交互式应用进行说明</p><pre style=\"width: 40%;\"><code># 利用代码块说明</code></pre>"
# appComment:
#   i18n:
#     default: |
#       <p>对上方交互式应用进行说明</p>
#       <pre style="width: 40%;"><code># 利用代码块说明</code></pre>
#     en: |
#       <p>Explanation of the app above</p>
#       <pre style="width: 40%;"><code># explanation with code</code></pre>
#     zh_cn: |
#       <p>对上方交互式应用进行说明</p>
#       <pre style="width: 40%;"><code># 利用代码块说明</code></pre>
