# 这个应用的ID
id: emacs

# 这个应用的名字
name: emacs

# 这个应用的图标文件在公共文件下的路径
# logoPath: /test.svg

# 指定应用类型，vnc或者web
type: vnc

# 可以运行这个应用的节点地址
# 如果不设置nodes，则所有节点都可以运行
# nodes:
#   - t001
#   - t002

# VNC应用的配置
vnc:
  # 此X Session的xstartup脚本
  xstartup: |
    emacs -mm
