version: "3"

services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - "db:/var/lib/mysql"
    ports:
      - 3306:3306

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  jobTableDb:
    image: mariadb:5.5
    environment:
      MYSQL_ROOT_PASSWORD: ${JOB_TABLE_PASSWORD}
    volumes:
      - jobtabledb:/var/lib/mysql
    ports:
      - 3307:3306

  ssh-server:
    image: lscr.io/linuxserver/openssh-server:latest
    ports:
      - 22222:2222
    environment:
      - PUID=1000
      - PGID=1000
      - USER_NAME=test
      - PASSWORD_ACCESS=true
      - SUDO_ACCESS=true
      - USER_PASSWORD=test
      - PUBLIC_KEY_FILE=/id_rsa.pub
    volumes:
      - ./ssh-server/custom-cont-init.d:/config/custom-cont-init.d
      - $HOME/.ssh/id_rsa.pub:/id_rsa.pub

  ldap:
    image: ldaptest
    build:
      context: ..
      dockerfile: dev/ldap/Dockerfile
    ports:
      - 389:389
    volumes:
      - ldap:/var/lib/ldap

networks:
  default:
    name: scow

volumes:
  db:
  ldap:
  jobtabledb:
