# 是否启用作业管理功能
jobManagement: true

# 登录节点桌面功能
loginDesktop:
  # 是否启用桌面功能
  enabled: true

  # 桌面
  wms:
    - name: KDE
      wm: 1-kde-plasma-standard
    - name: Xfce
      wm: xfce
    - name: MATE
      wm: mate
    - name: cinnamon
      wm: cinnamon

  # 最多启动多少个桌面节点
  maxDesktops: 3

# 是否启用交互式任务功能
apps: true

# 主页标题
homeTitle:
  # 默认文本
  defaultText: "Super Computing on Web"
  # defaultText:
  #   i18n:
  #     default: "超算平台"
  #     en: "Super Computing on Web"
  #     zh_cn: "超算平台"
  # 从不同域名访问，显示的不同的文本
  # hostnameMap:
  #   a.com: "a.com's SCOW Deployment"

# 主页文本
homeText:
  # 默认文本
  defaultText: "SCOW"
  # defaultText:
  #   i18n:
  #     default: "<p style='font-size: 16px;'>&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;项目通过简化集群软件的部署流程、统一平台管理模式、降低用户使用门槛，解决算力网络中计算资源管理难、使用难的问题。用户无需了解和配置SSH、VNC、命令行等，只需要一个浏览器就可以方便的使用集群算力资源。</p>"
  #     en: "<p style='font-size: 16px;'>&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;The project aims to simplify the deployment process of cluster software, unify platform management patterns, and reduce user barriers, addressing challenges in managing and utilizing computing resources within the computational network. Users do not need to understand or configure SSH, VNC, command lines, etc.; only a browser is required for convenient access to cluster computing resources.</p>"
  #     zh_cn: "<p style='font-size: 16px;'>&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;项目通过简化集群软件的部署流程、统一平台管理模式、降低用户使用门槛，解决算力网络中计算资源管理难、使用难的问题。用户无需了解和配置SSH、VNC、命令行等，只需要一个浏览器就可以方便的使用集群算力资源。</p>"
  # 从不同域名访问，显示的不同的文本
  # hostnameMap:
  #   a.com: "a.com's SCOW"

# 提交作业命令框中的提示语
# submitJobPromptText: "#此处参数设置的优先级高于页面其它地方，两者冲突时以此处为准"
# submitJobPromptText:
#   i18n:
#     default: 此处参数设置的优先级高于页面其它地方，两者冲突时以此处为准
#     en: The priority of the parameter settings here supersedes that of other areas on the page. In the event of a conflict, the settings here will prevail.
#     zh_cn: 此处参数设置的优先级高于页面其它地方，两者冲突时以此处为准

# 是否启用终端功能
shell: true

# 文件编辑大小限制
# 可接受的格式为nginx的client_max_body_size可接受的值
# fileEditSize: "1m"

# 提交作业的默认工作目录。使用{{ name }}代替作业名称。相对于用户的家目录
# submitJobDefaultPwd: scow/jobs/{{ name }}

# 将保存的作业保存到什么位置。相对于用户家目录
# savedJobsDir: scow/savedJobs

# 将交互式任务的信息保存到什么位置。相对于用户的家目录
# appJobsDir: scow/appData

# TurboVNC的安装路径
# turboVNCPath: /opt/TurboVNC

# # 新增导航链接相关配置
# navLinks:
#   # 链接名
#   - text: "一级导航1"
#     # 链接地址，一级导航链接地址为可选填，二级导航链接地址为必填
#     # url: ""
#     # 是否打开新的页面，可选填，默认值为false
#     # openInNewPage: true
#     # 图标路径，可选填
#     iconPath: ""
#     # 二级导航,可选填
#     children:
#       # 二级导航相关配置，与一级导航相同，但是url为必填配置，同时不允许再设置children
#       - text: "二级导航1"
#         url: "https://hahahaha1.1.com"
#         # openInNewPage: true
#         iconPath: ""
#       - text: "二级导航2"
#         url: "https://hahahaha1.2.com"
#         # openInNewPage: true
#         iconPath: ""
#   - text: "一级导航2"
#     url: "https://hahahaha2.com"
#     # openInNewPage: true
#     iconPath: ""
#     children: []
